//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lost()
        {
            this.Colors = new HashSet<Color>();
            this.Founds = new HashSet<Found>();
        }
    
        public decimal LostId { get; set; }
        public decimal CategoryId { get; set; }
        public decimal ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> MaterialId { get; set; }
        public string LostDescription { get; set; }
        public System.DateTime LostDate { get; set; }
        public double LostLat { get; set; }
        public double LostLng { get; set; }
        public decimal SearchRadius { get; set; }
        public string LostImage { get; set; }
        public decimal UserId { get; set; }
        public Nullable<decimal> color1 { get; set; }
        public Nullable<decimal> color2 { get; set; }
        public Nullable<decimal> color3 { get; set; }
        public string LostAddress { get; set; }
        public Nullable<bool> LostStatus { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual Color Color4 { get; set; }
        public virtual Color Color5 { get; set; }
        public virtual Item Item { get; set; }
        public virtual Material Material { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Color> Colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Found> Founds { get; set; }
    }
}
