//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HashavatAvedaEntities : DbContext
    {
        public HashavatAvedaEntities()
            : base("name=HashavatAvedaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Found> Founds { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Lost> Losts { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
